### ISSUE TITLE
关于无法使用账号密码登录的问题

### ISSUE THREAD

**Issue by Do1e** [Do1e/mijia-api#10]
大概率是由于异地登录触发了手机验证码。考虑到整套逻辑过于复杂，比如发送验证码所需的人机验证等，本项目就不进行实现了。

请尝试下述避开异地登录的方法：

1. 二维码登录一次后应该就行了。
2. 先使用对应的机器手动访问 https://account.xiaomi.com/ 登录一次。
3. 如果是不太方便使用浏览器的服务器，可以在本地使用ssh -D 1080 username@server_ip -N可快速创建socks5代理，之后使用SwitchyOmega浏览器拓展配置代理socks5://localhost:1080，最后登录 https://account.xiaomi.com/ 。（可以先访问IP查询网页确认代理配置成功）

**Comment by Do1e** [comment]
关联issues：

1. #2 
2. #8 
3. #9

**Comment by jh248** [comment]
触发异地登录有啥更好的解决办法吗？

**Comment by Do1e** [comment]
> 触发异地登录有啥更好的解决办法吗？

用二维码登录一次不是很好的解决办法吗？
