### ISSUE TITLE
请问一下成功登录获取到auth.json之后，在test_apis的时候获取scene list失败的问题

### ISSUE THREAD

**Issue by ChangMenQAQ** [Do1e/mijia-api#11]
代码在运行到scenes = api.get_scenes_list(home_id)['scene_info_list']的时候会抛出异常TypeError: 'NoneType' object is not subscriptable，但以上的device跟homes都正常获取到了，查看homes_id的值也一切正常不太理解是什么原因造成的

**Comment by Do1e** [comment]
应该是你没有设置手动控制，所以`get_scenes_list`对你没用，获取到的是空值`None`。
https://github.com/Do1e/mijia-api/blob/a803bab0bd098623499a4f52a3006afc6683b820/README.md?plain=1#L26
