### ISSUE TITLE
应该给个运行手动控制的demo，这样改下名字就能直接用了

### ISSUE THREAD

**Issue by aogg** [Do1e/mijia-api#13]

**Comment by Do1e** [comment]
毕竟每个人的情况都不完全一样。这个需求直接从[demos/test_apis.py](https://github.com/Do1e/mijia-api/blob/a803bab0bd098623499a4f52a3006afc6683b820/demos/test_apis.py#L24C1-L36C14)里把对应的片段摘出来就行了。
