### ISSUE TITLE
希望对 mijia API 库的 Python 版本依赖进行下调

### ISSUE THREAD

**Issue by Guangyaochenyu** [Do1e/mijia-api#18]
希望对 mijia API 库的 Python 版本依赖进行下调，用以拓展兼容性，让更多型号的设备能够适配并启用该库的最新版本，减少因版本适配问题而衍生的潜在风险与运维成本。

**Comment by Do1e** [comment]
0fe251e0370dbe17bed7a82ff21b3407a349665c

考虑到上游依赖，最低支持3.9
