### ISSUE TITLE
登录后 location里没有值

### ISSUE THREAD

**Issue by youzeliang** [Do1e/mijia-api#2]
登录后 location里没有值。这里取还不到      msg = request.get(result['location'])

**Comment by Do1e** [comment]
我没法复现你的问题，能给出更详细的信息吗？

**Comment by Do1e** [comment]
获取到的result是什么样的呢？
![image](https://github.com/Do1e/mijia-api/assets/73533898/dfc2067d-a9fd-4099-a7fb-e8a71af9b37a)

**Comment by youzeliang** [comment]
<img width="417" alt="image" src="https://github.com/Do1e/mijia-api/assets/26573169/faf2f2ed-f1b4-4a78-8530-ce06a456a8d1">  我下载下来，也就改了config.json 里的user和password

**Comment by Do1e** [comment]
这个字典里captchaUrl是有值的吗？

**Comment by Do1e** [comment]
哦哦，我看见了，没有。  result上面那个很长的Key是什么？

**Comment by youzeliang** [comment]
是notificationUrl

**Comment by CikeyQi** [comment]
我也遇到了同样的问题

**Comment by CikeyQi** [comment]
似乎找到了原因，location里没有值可能是异地登录引起的，在`https://account.xiaomi.com/`登录一遍，通过了设备锁，等待10分钟，就能正常登录了

**Comment by CikeyQi** [comment]
希望能增加扫码登录来解决这个问题，我自己研究了下发现除了 `serviceToken` 无法获取以外，其他必要的值都可以正常获取，大佬能看看有没有解决方法吗？

**Comment by Do1e** [comment]
有空我看看

**Comment by Do1e** [comment]
> 希望能增加扫码登录来解决这个问题，我自己研究了下发现除了 `serviceToken` 无法获取以外，其他必要的值都可以正常获取，大佬能看看有没有解决方法吗？
> 
> 我参考的项目是：[xiaomi-auth-sdk](https://github.com/miwufe/xiaomi-auth-sdk)

重构了代码，已经实现了
