### ISSUE TITLE
需要短信验证码

### ISSUE THREAD

**Issue by GxxkX** [Do1e/mijia-api#9]
账号密码登录有时需要短信验证码，且没有回调。
login接口返回以下数据

{'notificationUrl': 'https://account.xiaomi.com/identity/authStart?sid=xiaomiio&context=jGT9_3CtPRQskfJisM7lGZM2KcyD9QfmQNKFoajnBA&_locale=zh_CN', 'result': 'ok', 'code': 0, 'captchaUrl': None, 'description': '成功', 'location': '', 'securityStatus': 16, 'pwd': 0, 'child': 0, 'desc': '成功'}

**Comment by Do1e** [comment]
什么时候需要短信验证码呢？我这边没法复现。

实在不行建议使用二维码登录，登录一次可以使用很久。

**Comment by GxxkX** [comment]
应该是异地登录需要短信验证码，我在服务器运行登录的时候触发的

**Comment by Do1e** [comment]
有空我尝试一下

**Comment by Do1e** [comment]
考虑到整套逻辑过于复杂，比如发送验证码所需的人机验证等，这里就不进行实现了。

尝试下述避开异地登录的方法：
1. 二维码登录一次后应该就行了。
2. 先使用对应的机器手动访问 https://account.xiaomi.com/ 登录一次。
3. 如果是不太方便使用浏览器的服务器，可以在本地使用`ssh -D 1080 username@server_ip -N`可快速创建socks5代理，之后使用SwitchyOmega浏览器拓展配置代理socks5://localhost:1080，最后登录 https://account.xiaomi.com/ 。（可以先访问IP查询网页确认代理配置成功）
